import WidthBounds.PolynomialGeneratorNumber
import WidthBounds.GeneratorExact
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# The variable-ideal product and minimal coefficients

For an upper exponent set with a finite, complete set of minimal monomial
generators, vanishing at those generators cuts out the actual ideal product
`(x,y,z) * I` inside `I`. Completeness is expressed by an ideal-span equality.
No nonzero or proper-ideal hypothesis is imposed.
-/

namespace WidthBounds.MonomialInterface

noncomputable section

open MvPolynomial

variable {K : Type*} [Field K]

/-- The actual ideal generated by all three polynomial variables. -/
def variableIdeal : Ideal (MvPolynomial (Fin 3) K) :=
  Ideal.span (Set.range (MvPolynomial.X : Fin 3 → MvPolynomial (Fin 3) K))

theorem variableIdeal_mul_le (I : Ideal (MvPolynomial (Fin 3) K)) :
    variableIdeal * I ≤ I := Ideal.mul_le_left

theorem constantCoeff_eq_zero_of_mem_variableIdeal {p : MvPolynomial (Fin 3) K}
    (hp : p ∈ variableIdeal) : constantCoeff p = 0 := by
  have hle : variableIdeal (K := K) ≤ RingHom.ker constantCoeff := by
    apply Ideal.span_le.mpr
    rintro _ ⟨i, rfl⟩
    exact constantCoeff_X K i
  exact hle hp

/-- Every nonconstant coefficient-one monomial is in the variable ideal. -/
theorem monomial_mem_variableIdeal_of_ne_zero {d : Fin 3 →₀ ℕ} (hd : d ≠ 0) :
    monomial d (1 : K) ∈ variableIdeal := by
  classical
  change monomial d (1 : K) ∈ Ideal.span (Set.range X)
  rw [← Set.image_univ, mem_ideal_span_X_image]
  intro m hm
  have hdm : d = m := by simpa using hm
  subst m
  have hex : ∃ i, d i ≠ 0 := by
    by_contra h
    push_neg at h
    exact hd (Finsupp.ext h)
  obtain ⟨i, hi⟩ := hex
  exact ⟨i, Set.mem_univ i, hi⟩

/-- The variable-ideal product kills every minimal-generator coordinate. -/
theorem minimalCoefficientMap_eq_zero_of_mem_variableIdeal_mul
    (S : Set (Fin 3 →₀ ℕ)) (hUp : IsUpperSet S)
    (E : Finset (Fin 3 →₀ ℕ))
    (hMin : ∀ e ∈ E, IsMinimalExponent (monomialIdeal (R := K) S) e)
    {p : MvPolynomial (Fin 3) K}
    (hp : p ∈ variableIdeal (K := K) * monomialIdeal (R := K) S) :
    minimalCoefficientMap E p = 0 := by
  refine Submodule.mul_induction_on hp ?_ ?_
  · intro q hq r hr
    rw [minimalCoefficientMap_mul S hUp E hMin hr,
      constantCoeff_eq_zero_of_mem_variableIdeal hq, zero_smul]
  · intro q r hq hr
    rw [map_add, hq, hr, add_zero]

/-- Completeness of the finite monomial generating set gives the converse.
Every supported monomial has a strict generator divisor, hence a nonconstant
monomial factor from the variable ideal. -/
theorem mem_variableIdeal_mul_of_minimalCoefficientMap_eq_zero
    (S : Set (Fin 3 →₀ ℕ)) (hUp : IsUpperSet S)
    (E : Finset (Fin 3 →₀ ℕ))
    (hSpan : Ideal.span (exponentMonomials (R := K) E :
      Set (MvPolynomial (Fin 3) K)) = monomialIdeal S)
    {p : MvPolynomial (Fin 3) K} (hp : p ∈ monomialIdeal S)
    (hZero : minimalCoefficientMap E p = 0) :
    p ∈ variableIdeal (K := K) * monomialIdeal (R := K) S := by
  classical
  rw [p.as_sum]
  apply (variableIdeal (K := K) * monomialIdeal (R := K) S).sum_mem
  intro f hf
  have hfS := (mem_monomialIdeal_iff_support S hUp p).mp hp f hf
  have hfI := (monomial_mem_monomialIdeal_iff (R := K) S hUp f).mpr hfS
  rw [← hSpan, monomial_mem_span_exponentMonomials_iff] at hfI
  obtain ⟨e, he, hef⟩ := hfI
  have hfe : f ≠ e := by
    intro h
    have hc : coeff e p = 0 := congrFun hZero ⟨e, he⟩
    exact (mem_support_iff.mp hf) (h ▸ hc)
  have hd : f - e ≠ 0 := by
    intro hd
    have heq := tsub_add_cancel_of_le hef
    rw [hd, zero_add] at heq
    exact hfe heq.symm
  have heI : monomial e (1 : K) ∈ monomialIdeal S := by
    rw [← hSpan]
    apply Ideal.subset_span
    exact (monomial_mem_exponentMonomials_iff E e).mpr he
  have hec : monomial e (coeff f p) ∈ monomialIdeal S := by
    have h := (monomialIdeal (R := K) S).mul_mem_left (C (coeff f p)) heI
    simpa only [C_mul_monomial, mul_one] using h
  have hm := Ideal.mul_mem_mul (monomial_mem_variableIdeal_of_ne_zero (K := K) hd) hec
  simpa only [monomial_mul, one_mul, tsub_add_cancel_of_le hef] using hm

/-- Exact membership in the genuine product `(x,y,z) * I`, with the complete
finite minimal-monomial generating hypothesis retained explicitly. -/
theorem mem_variableIdeal_mul_monomialIdeal_iff
    (S : Set (Fin 3 →₀ ℕ)) (hUp : IsUpperSet S)
    (E : Finset (Fin 3 →₀ ℕ))
    (hMin : ∀ e ∈ E, IsMinimalExponent (monomialIdeal (R := K) S) e)
    (hSpan : Ideal.span (exponentMonomials (R := K) E :
      Set (MvPolynomial (Fin 3) K)) = monomialIdeal S)
    (p : MvPolynomial (Fin 3) K) :
    p ∈ variableIdeal (K := K) * monomialIdeal (R := K) S ↔
      p ∈ monomialIdeal S ∧ minimalCoefficientMap E p = 0 := by
  constructor
  · intro hp
    exact ⟨variableIdeal_mul_le _ hp,
      minimalCoefficientMap_eq_zero_of_mem_variableIdeal_mul S hUp E hMin hp⟩
  · rintro ⟨hp, hZero⟩
    exact mem_variableIdeal_mul_of_minimalCoefficientMap_eq_zero S hUp E hSpan hp hZero

#print axioms constantCoeff_eq_zero_of_mem_variableIdeal
#print axioms minimalCoefficientMap_eq_zero_of_mem_variableIdeal_mul
#print axioms mem_variableIdeal_mul_of_minimalCoefficientMap_eq_zero
#print axioms mem_variableIdeal_mul_monomialIdeal_iff

end

end WidthBounds.MonomialInterface
