import WidthBounds.FiniteColength

/-!
# A genuine finite-colength lex ideal for the lower construction

The complement of the exponent upper set is given by the division-free
condition `(i + 1) * (i + j + k + 1) ≤ s * s`.  This module realizes that
condition by membership in an actual polynomial ideal over any field.
Hilbert-function counts and budgets are established separately.
-/

namespace WidthBounds.Lower

noncomputable section

open MvPolynomial MonomialInterface

/-- The forbidden exponents of the explicit lower family. -/
def lowerExponentSet (s : ℕ) : Set (Fin 3 →₀ ℕ) :=
  {e | s * s < (e 0 + 1) * (e 0 + e 1 + e 2 + 1)}

theorem lowerExponentSet_isUpper (s : ℕ) : IsUpperSet (lowerExponentSet s) := by
  intro e f hef he
  exact lt_of_lt_of_le he (Nat.mul_le_mul (Nat.add_le_add_right (hef 0) 1)
    (by have h0 := hef 0; have h1 := hef 1; have h2 := hef 2; omega))

theorem lowerExponentSet_isLex (s : ℕ) : IsLexExponentSet (lowerExponentSet s) := by
  intro i j k i' j' k' hdeg hord hm
  have hi : i ≤ i' := by rcases hord with h | ⟨h, _⟩ <;> omega
  simp only [lowerExponentSet, Set.mem_setOf_eq, exponent_zero, exponent_one,
    exponent_two] at hm ⊢
  rw [← hdeg]
  exact lt_of_lt_of_le hm (Nat.mul_le_mul_right _ (Nat.add_le_add_right hi 1))

variable {K : Type*} [Field K]

/-- The actual monomial ideal generated by the forbidden exponent set. -/
def lowerIdeal (s : ℕ) : Ideal (MvPolynomial (Fin 3) K) :=
  monomialIdeal (lowerExponentSet s)

theorem monomial3_mem_lowerIdeal_iff (s i j k : ℕ) :
    monomial3 (R := K) i j k ∈ lowerIdeal s ↔
      s * s < (i + 1) * (i + j + k + 1) := by
  change monomial (exponent i j k) (1 : K) ∈ monomialIdeal (lowerExponentSet s) ↔ _
  rw [monomial_mem_monomialIdeal_iff _ (lowerExponentSet_isUpper s)]
  simp [lowerExponentSet]

theorem standard_lowerIdeal_iff (s i j k : ℕ) :
    standard (lowerIdeal (K := K) s) i j k ↔
      (i + 1) * (i + j + k + 1) ≤ s * s := by
  rw [standard, monomial3_mem_lowerIdeal_iff, not_lt]

theorem lowerIdeal_isLex (s : ℕ) : IsLex (lowerIdeal (K := K) s) :=
  monomialIdeal_isLex _ (lowerExponentSet_isUpper s) (lowerExponentSet_isLex s)

theorem lowerIdeal_standardLex (s : ℕ) :
    LexCounting.StandardLex (standard (lowerIdeal (K := K) s)) :=
  monomialIdeal_standardLex _ (lowerExponentSet_isUpper s) (lowerExponentSet_isLex s)

theorem pure_z_mem_lowerExponentSet (s : ℕ) :
    exponent 0 0 (s * s) ∈ lowerExponentSet s := by
  simp [lowerExponentSet]

theorem pure_z_mem_lowerIdeal (s : ℕ) :
    monomial3 (R := K) 0 0 (s * s) ∈ lowerIdeal s := by
  rw [monomial3_mem_lowerIdeal_iff]
  simp

theorem lowerExponentSet_standard_finite (s : ℕ) : (lowerExponentSet s)ᶜ.Finite :=
  standard_finite_of_pure_z _ (lowerExponentSet_isUpper s) (lowerExponentSet_isLex s)
    (pure_z_mem_lowerExponentSet s)

/-- Finite colength means finite-dimensionality of this actual quotient. -/
theorem lowerIdeal_quotient_finite (s : ℕ) :
    Module.Finite K (MvPolynomial (Fin 3) K ⧸ lowerIdeal s) :=
  (quotient_finite_iff_standard_finite _ (lowerExponentSet_isUpper s)).mpr
    (lowerExponentSet_standard_finite s)

theorem pure_x_mem_lowerIdeal (s : ℕ) :
    monomial3 (R := K) s 0 0 ∈ lowerIdeal s := by
  rw [monomial3_mem_lowerIdeal_iff]
  simp only [Nat.add_zero]
  nlinarith

theorem pure_x_standard_of_lt {s d : ℕ} (hd : d < s) :
    standard (lowerIdeal (K := K) s) d 0 0 := by
  rw [standard_lowerIdeal_iff]
  simp only [Nat.add_zero]
  exact Nat.mul_le_mul (by omega) (by omega)

/-- All total degrees below `s` are standard, so the initial degree is exactly `s`. -/
theorem standard_lowerIdeal_of_degree_lt {s i j k : ℕ} (hd : i + j + k < s) :
    standard (lowerIdeal (K := K) s) i j k := by
  rw [standard_lowerIdeal_iff]
  exact Nat.mul_le_mul (by omega) (by omega)

/-- An equivalent threshold form, valid even below the initial degree. -/
theorem standard_lowerIdeal_iff_lt_div (s i j k : ℕ) :
    standard (lowerIdeal (K := K) s) i j k ↔ i < s * s / (i + j + k + 1) := by
  rw [standard_lowerIdeal_iff,
    ← Nat.le_div_iff_mul_le (by omega : 0 < i + j + k + 1)]
  omega

/-- Exact agreement with the original construction using a degree cutoff and
the floor threshold. The cutoff is redundant for the product presentation. -/
theorem monomial3_mem_lowerIdeal_iff_piecewise (s i j k : ℕ) :
    monomial3 (R := K) i j k ∈ lowerIdeal s ↔
      s ≤ i + j + k ∧ s * s / (i + j + k + 1) ≤ i := by
  have hThreshold : monomial3 (R := K) i j k ∈ lowerIdeal s ↔
      s * s / (i + j + k + 1) ≤ i := by
    have h := not_congr (standard_lowerIdeal_iff_lt_div (K := K) s i j k)
    simpa only [standard, not_not, not_lt] using h
  constructor
  · intro hm
    refine ⟨?_, hThreshold.mp hm⟩
    by_contra hdeg
    exact standard_lowerIdeal_of_degree_lt (by omega) hm
  · intro hm
    exact hThreshold.mpr hm.2

theorem lowerIdeal_initial_degree (s : ℕ) :
    ¬ standard (lowerIdeal (K := K) s) s 0 0 ∧
      ∀ i j k, i + j + k < s → standard (lowerIdeal (K := K) s) i j k := by
  exact ⟨not_not.mpr (pure_x_mem_lowerIdeal s), fun _ _ _ hd =>
    standard_lowerIdeal_of_degree_lt hd⟩

theorem x_standard_lowerIdeal {s : ℕ} (hs : 2 ≤ s) :
    standard (lowerIdeal (K := K) s) 1 0 0 :=
  pure_x_standard_of_lt (by omega)

theorem lowerIdeal_ne_bot (s : ℕ) : lowerIdeal (K := K) s ≠ ⊥ :=
  (monomialIdeal_ne_bot_iff _).mpr ⟨exponent 0 0 (s * s), pure_z_mem_lowerExponentSet s⟩

theorem monomial3_mem_lowerIdeal_of_degree_ge {s i j k : ℕ} (hd : s * s ≤ i + j + k) :
    monomial3 (R := K) i j k ∈ lowerIdeal s := by
  rw [monomial3_mem_lowerIdeal_iff]
  have hmul : 1 * (i + j + k + 1) ≤ (i + 1) * (i + j + k + 1) :=
    Nat.mul_le_mul_right _ (by omega)
  nlinarith

#print axioms lowerExponentSet_isUpper
#print axioms lowerExponentSet_isLex
#print axioms standard_lowerIdeal_iff
#print axioms lowerIdeal_quotient_finite
#print axioms lowerIdeal_initial_degree
#print axioms monomial3_mem_lowerIdeal_iff_piecewise

end

end WidthBounds.Lower
