import WidthBounds.LexCounting
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# A concrete monomial-ideal interface for `StandardLex`

The coefficient-one monomials below live in an actual `MvPolynomial (Fin 3) R`
and membership is actual `Ideal` membership. Ideal closure proves the divisibility
part of `StandardLex`; only same-degree lex closure is a separate hypothesis.

For an upward closed set of exponents, the ideal generated by its monomials has
exactly that set of coefficient-one monomials. This uses mathlib's support
criterion for membership in a monomial ideal, not an assumed correspondence.
No quotient Hilbert-function, finite-colength, or Betti-number identification is
claimed here.
-/

namespace WidthBounds.MonomialInterface

noncomputable section

open MvPolynomial

/-- Coordinates `0, 1, 2` stand for `x, y, z`, in that lexicographic order. -/
def exponent (i j k : ℕ) : Fin 3 →₀ ℕ :=
  Finsupp.single 0 i + Finsupp.single 1 j + Finsupp.single 2 k

@[simp] theorem exponent_zero (i j k : ℕ) : exponent i j k 0 = i := by
  simp [exponent]

@[simp] theorem exponent_one (i j k : ℕ) : exponent i j k 1 = j := by
  simp [exponent]

@[simp] theorem exponent_two (i j k : ℕ) : exponent i j k 2 = k := by
  simp [exponent]

theorem exponent_coordinates (e : Fin 3 →₀ ℕ) : exponent (e 0) (e 1) (e 2) = e := by
  ext v
  fin_cases v <;> simp

theorem exponent_le_iff {i j k i' j' k' : ℕ} :
    exponent i j k ≤ exponent i' j' k' ↔ i ≤ i' ∧ j ≤ j' ∧ k ≤ k' := by
  constructor
  · intro h
    exact ⟨by simpa using h 0, by simpa using h 1, by simpa using h 2⟩
  · rintro ⟨hi, hj, hk⟩ v
    fin_cases v <;> simpa using (by assumption : _ ≤ _)

variable {R : Type*} [CommSemiring R]

/-- The coefficient-one monomial `x^i y^j z^k`. -/
def monomial3 (i j k : ℕ) : MvPolynomial (Fin 3) R := monomial (exponent i j k) 1

/-- Standardness is nonmembership in a genuine polynomial ideal. -/
def standard (I : Ideal (MvPolynomial (Fin 3) R)) (i j k : ℕ) : Prop :=
  monomial3 i j k ∉ I

/-- Same-degree lex upper closure, with variable order `x > y > z`.
The definition makes no assertion about arbitrary polynomials or homogeneity. -/
def IsLex (I : Ideal (MvPolynomial (Fin 3) R)) : Prop :=
  ∀ {i j k i' j' k' : ℕ}, i + j + k = i' + j' + k' →
    (i < i' ∨ (i = i' ∧ j ≤ j')) → monomial3 i j k ∈ I → monomial3 i' j' k' ∈ I

/-- Ideal multiplication supplies upward closure under monomial divisibility. -/
theorem monomial3_mem_of_le (I : Ideal (MvPolynomial (Fin 3) R))
    {i j k i' j' k' : ℕ} (hi : i ≤ i') (hj : j ≤ j') (hk : k ≤ k')
    (hm : monomial3 i j k ∈ I) : monomial3 i' j' k' ∈ I := by
  apply I.mem_of_dvd _ hm
  apply monomial_dvd_monomial.mpr
  exact ⟨Or.inr (exponent_le_iff.mpr ⟨hi, hj, hk⟩), dvd_rfl⟩

/-- The combinatorial closure hypotheses follow from actual ideal membership. -/
theorem standardLex (I : Ideal (MvPolynomial (Fin 3) R)) (hLex : IsLex I) :
    LexCounting.StandardLex (standard I) where
  down hi hj hk hm hsmall := hm (monomial3_mem_of_le I hi hj hk hsmall)
  lex hdeg hord hm hsmall := hm (hLex hdeg hord hsmall)

/-- An ideal generated by the coefficient-one monomials with exponents in `S`. -/
def monomialIdeal (S : Set (Fin 3 →₀ ℕ)) : Ideal (MvPolynomial (Fin 3) R) :=
  Ideal.span ((fun e => monomial e (1 : R)) '' S)

/-- For an exponent upper set, polynomial membership is equivalent to every
supported exponent belonging to the set. -/
theorem mem_monomialIdeal_iff_support (S : Set (Fin 3 →₀ ℕ))
    (hUp : IsUpperSet S) (p : MvPolynomial (Fin 3) R) :
    p ∈ monomialIdeal S ↔ ∀ e ∈ p.support, e ∈ S := by
  rw [monomialIdeal, mem_ideal_span_monomial_image]
  constructor
  · intro h e he
    obtain ⟨s, hs, hse⟩ := h e he
    exact hUp hse hs
  · intro h e he
    exact ⟨e, h e he, le_rfl⟩

variable [Nontrivial R]

/-- In a nontrivial coefficient semiring, a monomial ideal is nonzero exactly
when its generating exponent set is nonempty. No upward-closure assumption is needed. -/
theorem monomialIdeal_ne_bot_iff (S : Set (Fin 3 →₀ ℕ)) :
    monomialIdeal (R := R) S ≠ ⊥ ↔ S.Nonempty := by
  constructor
  · intro h
    by_contra hS
    have hEmpty : S = ∅ := Set.not_nonempty_iff_eq_empty.mp hS
    apply h
    simp [hEmpty, monomialIdeal]
  · rintro ⟨e, he⟩ hbot
    have hm : monomial e (1 : R) ∈ monomialIdeal S := Ideal.subset_span ⟨e, he, rfl⟩
    rw [hbot, Ideal.mem_bot, monomial_eq_zero] at hm
    exact one_ne_zero hm

/-- Exact membership, derived from mathlib's support criterion. -/
theorem monomial_mem_monomialIdeal_iff (S : Set (Fin 3 →₀ ℕ))
    (hUp : IsUpperSet S) (e : Fin 3 →₀ ℕ) :
    monomial e (1 : R) ∈ monomialIdeal S ↔ e ∈ S := by
  classical
  rw [monomialIdeal, mem_ideal_span_monomial_image]
  simp only [support_monomial, one_ne_zero, ↓reduceIte, Finset.mem_singleton]
  constructor
  · intro h
    obtain ⟨s, hs, hse⟩ := h e rfl
    exact hUp hse hs
  · intro he d hd
    subst d
    exact ⟨e, he, le_rfl⟩

/-- Same-degree lex upper closure formulated directly on an exponent set. -/
def IsLexExponentSet (S : Set (Fin 3 →₀ ℕ)) : Prop :=
  ∀ {i j k i' j' k' : ℕ}, i + j + k = i' + j' + k' →
    (i < i' ∨ (i = i' ∧ j ≤ j')) → exponent i j k ∈ S → exponent i' j' k' ∈ S

theorem monomialIdeal_isLex (S : Set (Fin 3 →₀ ℕ)) (hUp : IsUpperSet S)
    (hLex : IsLexExponentSet S) : IsLex (monomialIdeal (R := R) S) := by
  intro i j k i' j' k' hdeg hord hm
  apply (monomial_mem_monomialIdeal_iff S hUp _).mpr
  exact hLex hdeg hord ((monomial_mem_monomialIdeal_iff S hUp _).mp hm)

/-- Concrete bridge: the complement of the generated polynomial ideal is StandardLex. -/
theorem monomialIdeal_standardLex (S : Set (Fin 3 →₀ ℕ)) (hUp : IsUpperSet S)
    (hLex : IsLexExponentSet S) :
    LexCounting.StandardLex (standard (monomialIdeal (R := R) S)) :=
  standardLex _ (monomialIdeal_isLex S hUp hLex)

theorem standard_monomialIdeal_iff (S : Set (Fin 3 →₀ ℕ)) (hUp : IsUpperSet S)
    (i j k : ℕ) : standard (monomialIdeal (R := R) S) i j k ↔ exponent i j k ∉ S :=
  not_congr (monomial_mem_monomialIdeal_iff S hUp _)

omit [Nontrivial R]

/-- Every monomial in a lex ideal forces the pure `x` power of the same degree. -/
theorem pure_x_mem_of_monomial_mem (I : Ideal (MvPolynomial (Fin 3) R))
    (hLex : IsLex I) {i j k : ℕ} (hm : monomial3 i j k ∈ I) :
    monomial3 (i + j + k) 0 0 ∈ I := by
  apply hLex (by omega) _ hm
  by_cases hi : i < i + j + k
  · exact Or.inl hi
  · exact Or.inr ⟨by omega, by omega⟩

/-- A nonempty generating set in a lex monomial ideal supplies a forbidden pure power.
Finite colength is not needed for this implication. -/
theorem exists_pure_x_mem (S : Set (Fin 3 →₀ ℕ))
    (hLex : IsLex (monomialIdeal (R := R) S)) (hS : S.Nonempty) :
    ∃ a : ℕ, monomial3 a 0 0 ∈ monomialIdeal (R := R) S := by
  obtain ⟨e, he⟩ := hS
  refine ⟨e 0 + e 1 + e 2, pure_x_mem_of_monomial_mem _ hLex ?_⟩
  change monomial (exponent (e 0) (e 1) (e 2)) (1 : R) ∈ _
  rw [exponent_coordinates]
  exact Ideal.subset_span ⟨e, he, rfl⟩

/-- The least forbidden pure power supplies precisely `hx` and `hInitial`.
Excluding the constant and linear pure powers yields the lower bound `2`. -/
theorem exists_initial_degree (I : Ideal (MvPolynomial (Fin 3) R))
    (hExists : ∃ a : ℕ, monomial3 a 0 0 ∈ I)
    (hZero : standard I 0 0 0) (hOne : standard I 1 0 0) :
    ∃ a : ℕ, 2 ≤ a ∧ ¬ standard I a 0 0 ∧ ∀ d, d < a → standard I d 0 0 := by
  classical
  refine ⟨Nat.find hExists, ?_, ?_, ?_⟩
  · have hm := Nat.find_spec hExists
    by_contra hlt
    have ha : Nat.find hExists = 0 ∨ Nat.find hExists = 1 := by omega
    rcases ha with ha | ha
    · apply hZero
      simpa only [ha] using hm
    · apply hOne
      simpa only [ha] using hm
  · exact not_not.mpr (Nat.find_spec hExists)
  · intro d hd
    exact Nat.find_min hExists hd

/-- A nonzero lex monomial ideal with `x` standard has a genuine initial total
degree at least two; all lower-degree monomials are standard. -/
theorem monomialIdeal_exists_initial_degree [Nontrivial R]
    (S : Set (Fin 3 →₀ ℕ)) (hUp : IsUpperSet S) (hLex : IsLexExponentSet S)
    (hNonzero : monomialIdeal (R := R) S ≠ ⊥)
    (hOne : standard (monomialIdeal (R := R) S) 1 0 0) :
    ∃ a : ℕ, 2 ≤ a ∧ ¬ standard (monomialIdeal (R := R) S) a 0 0 ∧
      (∀ d, d < a → standard (monomialIdeal (R := R) S) d 0 0) ∧
      ∀ i j k, i + j + k < a → standard (monomialIdeal (R := R) S) i j k := by
  have hLI : IsLex (monomialIdeal (R := R) S) := monomialIdeal_isLex S hUp hLex
  have hSL := monomialIdeal_standardLex (R := R) S hUp hLex
  have hExists := exists_pure_x_mem S hLI ((monomialIdeal_ne_bot_iff S).mp hNonzero)
  have hZero := hSL.down (by omega : 0 ≤ 1) le_rfl le_rfl hOne
  obtain ⟨a, ha, hx, hInitial⟩ := exists_initial_degree _ hExists hZero hOne
  refine ⟨a, ha, hx, hInitial, ?_⟩
  intro i j k hdeg hm
  exact hInitial (i + j + k) hdeg (pure_x_mem_of_monomial_mem _ hLI hm)

#print axioms monomial_mem_monomialIdeal_iff
#print axioms monomialIdeal_standardLex
#print axioms exists_initial_degree
#print axioms monomialIdeal_exists_initial_degree

end

end WidthBounds.MonomialInterface
